### ISSUE TITLE
Recommendations to implement this project to an existing Codeigniter 3 project

### ISSUE THREAD

**Issue by titosobabas** [ngekoding/codeigniter-vue-boilerplate#1]
Hi! This is Fernando. I would like firstly to thank you regarding this awesome project. Besides, I would appreciate if you have some recommendations in order to implement this solution to an existing Codeigniter 3 project. I've been working with this amazing framework during the last 4 years and now I would like to implement Vue 2 and your project looks wonderful. 
Thank you.

**Comment by ngekoding** [comment]
It is so easy to implement into existing project, you just need to copy the `frontend` folder. Then look to these files (already mentioned in readme)

- application/helpers/vite_helper.php
- application/controllers/Vue.php
- application/config/routes.php
- application/views/index.vue.php

And the last one is to follow the [Running the project](https://github.com/ngekoding/codeigniter-vue-boilerplate/tree/vue2#running-the-project) part
